name: React app deployment

on:
  push:
    branches: ["master"]  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.4'  

      - name: Install dependencies
        run: npm install
      - name: Create .env file
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" >> .env
          
      - name: Build project
        run: npm run build 

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Copy file and folder to S3
        run: |
          
          aws s3 cp dist/index.html s3://react-app-bucket-assignment-1/index.html
         
          aws s3 cp dist/vite.svg s3://react-app-bucket-assignment-1/vite.svg
         
          aws s3 cp dist/assets s3://react-app-bucket-assignment-1/assets --recursive